workflows:
  android-capacitor:
    name: Android Capacitor Build
    max_build_duration: 120
    instance_type: mac_mini_m1
    triggering:
      events:
        - push
        - tag
        - pull_request
      branch_patterns:
        - pattern: main
          include: true
          source: true
        - pattern: develop
          include: true
          source: true
    environment:
      groups:
        - google_play # Google Play Store credentials
      vars:
        PACKAGE_NAME: "com.smartpedi.app"
        GOOGLE_PLAY_TRACK: internal
        NODE_VERSION: 18
      node: 18
      java: 17
    scripts:
      - name: Install dependencies
        script: |
          npm ci
      
      - name: Build web app
        script: |
          npm run build
      
      - name: Install Capacitor
        script: |
          npm install -g @capacitor/cli
          npm install @capacitor/core @capacitor/android
          npm install @capacitor/splash-screen @capacitor/push-notifications @capacitor/local-notifications
      
      - name: Initialize Capacitor
        script: |
          if [ ! -f "capacitor.config.ts" ]; then
            npx cap init SmartPedi com.smartpedi.app --web-dir=dist
          fi
      
      - name: Add Android platform
        script: |
          npx cap add android
      
      - name: Sync Capacitor
        script: |
          npx cap sync android
      
      - name: Set up local.properties
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"
      
      - name: Build Android APK
        script: |
          cd android
          ./gradlew assembleRelease --stacktrace
    
    artifacts:
      - android/app/build/outputs/**/*.apk
      - android/app/build/outputs/**/mapping.txt
    
    publishing:
      email:
        recipients:
          - mrmaftunbek@gmail.com
        notify:
          success: true
          failure: true
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: $GOOGLE_PLAY_TRACK
        submit_as_draft: true

  android-debug:
    name: Android Debug Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: develop
          include: true
          source: true
    environment:
      vars:
        NODE_VERSION: 18
      node: 18
      java: 17
    scripts:
      - name: Install dependencies
        script: |
          npm ci
      
      - name: Build web app
        script: |
          npm run build
      
      - name: Install Capacitor
        script: |
          npm install -g @capacitor/cli
          npm install @capacitor/core @capacitor/android
      
      - name: Add Android platform
        script: |
          npx cap add android
      
      - name: Sync Capacitor
        script: |
          npx cap sync android
      
      - name: Set up local.properties
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"
      
      - name: Build Android Debug APK
        script: |
          cd android
          ./gradlew assembleDebug
    
    artifacts:
      - android/app/build/outputs/**/*.apk
    
    publishing:
      email:
        recipients:
          - developer@smartpedi.com
        notify:
          success: true
          failure: true

  ios-capacitor:
    name: iOS Capacitor Build
    max_build_duration: 120
    instance_type: mac_mini_m1
    triggering:
      events:
        - push
        - tag
      branch_patterns:
        - pattern: main
          include: true
          source: true
    environment:
      groups:
        - app_store_connect # App Store Connect credentials
      vars:
        BUNDLE_ID: "com.smartpedi.app"
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"
      node: 18
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: |
          npm ci
      
      - name: Build web app
        script: |
          npm run build
      
      - name: Install Capacitor
        script: |
          npm install -g @capacitor/cli
          npm install @capacitor/core @capacitor/ios
      
      - name: Add iOS platform
        script: |
          npx cap add ios
      
      - name: Sync Capacitor
        script: |
          npx cap sync ios
      
      - name: Set up code signing
        script: |
          keychain initialize
          app-store-connect fetch-signing-files $BUNDLE_ID --type IOS_APP_STORE --create
          keychain add-certificates
          xcode-project use-profiles
      
      - name: Build iOS
        script: |
          xcode-project build-ipa --workspace "$XCODE_WORKSPACE" --scheme "$XCODE_SCHEME"
    
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
    
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        beta_groups:
          - SmartPedi Beta Testers
        submit_to_app_store: false